openapi: 3.0.3
info:
  title: Middleware API
  description: API documentation for the banking middleware
  version: 1.0.0
servers:
  - url: http://localhost:8090
    description: Local development server
paths:
  /api/consult-account:
    get:
      summary: Consult account details by ID
      description: Retrieve account information from CBS
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
          description: The account ID to consult
      responses:
        '200':
          description: Successfully retrieved account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '404':
          description: Account not found
  /api/consult-customer:
    get:
      summary: Consult customer details by ID
      description: Retrieve customer information from CBS
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
          description: The customer ID to consult
      responses:
        '200':
          description: Successfully retrieved customer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: Customer not found
  /api/consult-history:
    get:
      summary: Consult transaction history by account ID
      description: Retrieve the last 10 transactions for an account from CBS
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
          description: The account ID to consult history for
      responses:
        '200':
          description: Successfully retrieved transaction history
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '404':
          description: History not found
  /api/do-transfer:
    post:
      summary: Perform a fund transfer between accounts
      description: Execute a transfer and update balances
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequest'
      responses:
        '200':
          description: Transfer successful
          content:
            text/plain:
              schema:
                type: string
                example: "Transfer successful"
        '500':
          description: Transfer failed
          content:
            text/plain:
              schema:
                type: string
                example: "Transfer failed"
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: string
        accountNumber:
          type: string
        balance:
          type: number
        customerId:
          type: string
    Customer:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        address:
          type: string
        email:
          type: string
    Transaction:
      type: object
      properties:
        type:
          type: string
        amount:
          type: number
        date:
          type: string
    TransferRequest:
      type: object
      properties:
        id:
          type: string
        fromAccountId:
          type: string
        toAccountId:
          type: string
        amount:
          type: number
    TransferResponse:
      type: object
      properties:
        status:
          type: string
        fromBalance:
          type: number
        toBalance:
          type: number